### ISSUE TITLE
不符合PS标准

### ISSUE THREAD

**Issue by hyg** [SarahZhao2022/Septem_public#1]
https://github.com/SarahZhao2022/Septem_public/blob/030dbd36f3e1be090516f0bb11cae619edd028ef/%C2%A0%E9%A1%B9%E7%9B%AE%E5%B7%A5%E4%BD%9C%E6%A8%A1%E5%9E%8B#L6
根据[讨论](https://github.com/SarahZhao2022/Septem_public/commit/030dbd36f3e1be090516f0bb11cae619edd028ef#r75129119)，董事长准备在《公司章程》中定义。
因此《项目工作模型 》并不是独立的模型，而是部门级规章，所属层级是：
《公司章程》、《股东会议事规则》 → 股东会决议（董事任免）→ （董事会制定）《董事会议事规则》→  董事会决议（召集人任免） → （召集人制定）《项目工作模型 》

根据PSMD的[PS标准](项目工作模型 )，
上级规章未生效（或被实质架空）时，不提交、不讨论下级规章。
上级人员未赴任（或被实质架空）时，不提名、不讨论下级人员。

如果坚持上面的[讨论](https://github.com/SarahZhao2022/Septem_public/commit/030dbd36f3e1be090516f0bb11cae619edd028ef#r75129119)，就要在《公司章程》、《股东会议事规则》 、股东会决议（董事任免）、《董事会议事规则》、董事会决议（召集人任免）生效，且召集人赴任之后，再讨论本模型。
除此以外，《项目工作模型 》内容可能和《公司章程》还有许多冲突。

或者取消上面的[讨论](https://github.com/SarahZhao2022/Septem_public/commit/030dbd36f3e1be090516f0bb11cae619edd028ef#r75129119)，另外说明召集人的产生和卸任，确保本模型是独立的顶级规章，代替公司章程等文件。

**Comment by SarahZhao2022** [comment]
已经在新版工作模型里修订， 工作模型作为独立工作的模型，为Septem公司章程。故关闭此issue。
