### ISSUE TITLE
早期项目负责人的任免权

### ISSUE THREAD

**Issue by hyg** [SarahZhao2022/Septem_public#2]
https://github.com/SarahZhao2022/Septem_public/blob/cbc93eeafd3a16201d5ffb25bb68476a0af6b543/%C2%A0%E9%A1%B9%E7%9B%AE%E5%B7%A5%E4%BD%9C%E6%A8%A1%E5%9E%8B#L22

召集人任免项目负责人这份设定，权责并不平衡。
召集人只有起草《Septom项目工作模型》的责任，相对于项目负责人的任免权来说，权力远远超过责任。

结合历史案例，召集人很可能要兼任其它职位，并且与项目负责人之间形成利益捆绑。也就是说，任免权不是用来冲抵起草《Septom项目工作模型》付出的劳动，而是用来寻租（比如在兼任的其它职务上互相掩盖工作失误）。

修改思路：
1. 参考[FOOD.COOP项目](https://github.com/hyg/com.origin/blob/master/Food.COOP/food.coop.com.md)的条款，召集人承担保底人职责（自己做或者自己掏钱请人做）。以这项责任对应早期项目负责人的任免权。一旦召集人在保底人职责上失职，他的任免决策就自动失效。
2. 参考[1609模型](https://github.com/hyg/com.origin/blob/master/1609/com.md)的条款。没有召集人这个角色，设立共同体则成为首任部署者，部署者担任首届director。一旦他在director角色上失职，他在director角色上的权力也自动失效。

以上两种的权责搭配，在大部分人眼里比目前版本更公平。
注意：两个范例中的任免权条款，都要和来源模型的其它条款紧密结合，才能产生预期效果。

**Comment by SarahZhao2022** [comment]
1 本项目冷启动，启动期和更新期的主要劳动报酬都以股份形式支付，相对本issue提出的可能存在的不公平，更主要的挑战在于如何组织项目组成员有效工作，故暂时不主张修订；
2 我会保持本议题持续开放，鼓励项目参与人置评

**Comment by hyg** [comment]
> 

按照这个思路，可以设计第3种修改思路：

- 召集人起草《Septom项目工作模型》付出的劳动可以提出报酬，一并以股份形式支付。对应的，去掉召集人的人事任免权（因为召集人已经没有其它可以交换的责任）。
- 作为配套，项目负责人的竞聘产生：
   - 竞聘者提交《工作计划和预算案》，包括各角色的合同；
   - 开放招募项目成员，签署某个竞聘者的《工作计划和预算案》中的某个角色合同；
   - 期限结束时，召集人选择一份所有角色都有人签署的《工作计划和预算案》，提交的竞聘者即出任项目负责人。
   - 期限结束时，任何一份《工作计划和预算案》都没有完整的人员班子签字，就按照启动失败处理。

这个思路下，召集人也不需要承担起草《Septom项目工作模型》以外的劳动，但是也失去权力寻租的隐患。

**Comment by hyg** [comment]
如果召集人权责不平衡，应该不会有人认为规章还有作用。

整个企业会陷入常见的情况：
1. 实际控制人和他的既得利益小集团会在封闭情况下协商处理问题，分配他们集团内部的权利，而不使用规章。
2. 这个小集团也不能使用规章约束其他员工的失职（懒惰、业务能力低、甚至营私舞弊...）。而是靠人对人的盯防去推动员工，个人的时间精力被大量消耗在这种盯防上，而不是去创造利润。
3. 这个小集团和外围员工之间的过招，不会有书面记录（各自都有违规甚至违法的情形，而且也各种都掌握一些证据）。因此无论政府部门还是不在场的朋友，都没有办法提供帮助。

这种情况主要问题就是时间精力能不能支撑这种高强敌的无规章人盯人。

**Comment by hyg** [comment]
如果召集人权责不平衡，应该不会有人认为规章还有作用。

整个企业会陷入常见的情况：
1. 实际控制人和他的既得利益小集团会在封闭情况下协商处理问题，分配他们小集团内部的权利，而不使用规章。
2. 这个小集团也不能使用规章约束其他员工的失职（懒惰、业务能力低、甚至营私舞弊...）。而是靠人对人的盯防去推动员工，个人的时间精力被大量消耗在这种盯防上，而不是去创造利润。
3. 这个小集团和外围员工之间的过招，不会有书面记录（各自都有违规甚至违法的情形，而且也都掌握一些证据）。因此无论政府部门还是不在场的朋友，都没有办法提供帮助。

这种情况主要问题就是时间精力能不能支撑这种高强度的无规章人盯人。

**Comment by hyg** [comment]
关于《[Septem项目工作模型]([cbc93ee](https://github.com/SarahZhao2022/Septem_public/commit/cbc93eeafd3a16201d5ffb25bb68476a0af6b543))》37、39、60、64行使用的“股份”。

- 《Septem项目工作模型》中这个术语和公司法中同名术语的定义不同，在上级职位的渎职、违规、贪腐等问题不能解决的情况下，员工倾向于接受现金报酬而不是这种“股份”。
- 税后报酬购买股份，符合所有情况的法律和司法解释。这个环节只有避税问题，不存在可行性问题。
- 由于这个“股份”定义由召集人（通过修订《Septem项目工作模型》）和项目负责人（通过目前还没有添加的规章或直接指挥）产生。根据PS标准，召集人和项目负责人的任免程序未生效、人员未赴任前，不提交、不讨论下级规章。（召集人和项目负责人的任免程序制定过程可以讨论他们工作场景，包括他们制定下级规章的场景。只有特定任免程序导致特定下级规章预案不能产生，引入讨论才有意义。一旦离开召集人、项目负责人任免程序讨论的时间、地点、人员这些条件就不能提前讨论下级规章，因为在正式赴任之前以这些职位的身份提前工作，是暗示自己的内定角色。）

因此，应该由解决召集人、项目负责人等职位的渎职、违规、贪腐问题的方案，以及根据该方案产生的人员，决定是否在现金报酬以外增加延后支付的形式，根据当时生效的上层规章决定延后支付的报酬相关规章条款，进一步判断是否存在避税问题以及如何解决。

**Comment by hyg** [comment]
约定按照 [项目工作模型 版本030dbd3](https://github.com/SarahZhao2022/Septem_public/commit/030dbd36f3e1be090516f0bb11cae619edd028ef)执行一段时间。如果能严格执行这份文件，在产生连续几个季度的真实工作记录之后，再根据当时情况提供力所能及的帮助。
